### PR TITLE
work in progress using mongo native driver and promises

### PR DESCRIPTION
**Pull request by dcsan**
@mvaragnat this is for reference only

I ported to using the native mongo 2.1 driver which supports promises.
this means no deps on monk or any of those other flaky drivers.
the 2.1 mongo driver itself is fairly feature full.

mongo itself is connecting fine, and returns a promise
https://github.com/dcsan/botkit-express-demo/blob/master/app/controllers/botkit.js#L22

however, the whole initialization process of the app is just using `require(xxx)` type structure, so I'm not really sure how to get things to work without a huge refactoring to make it more promise driven.

maybe someone on the howdy team would have some ideas?

for my new code i would prefer to work with mongo in this way but don't see how to get botkit refactored.

I also did some tests with other mongo drivers and using co() and await syntax 
https://github.com/dcsan/mongo-driver-comparison/blob/master/test/es6-test.js

again this would mean some refactoring at the top level to be `co` aware...

let me know if you have any thoughts.

another way is using typescript which already supports the `await` syntax
https://github.com/dcsan/mongo-driver-comparison/blob/master/test/typescript-await-demo.ts

but not sure anyone on botkit would want to go there - it would narrow down the possible contributors a lot.

### CODE REVIEW

**Comment by mvaragnat** [comment]
Thanks man - I'm not so familiar with promises myself, but it looks much better.

In the meanwhile - if you're ok I'll close the pull request? This repo is just intended to be a very simple demo. Perhaps let's open another repo to fork botkit itself?

**Comment by dcsan** [comment]
sure go ahead and close it out.

**Comment by dcsan** [comment]
I was thinking there is no need for the storage to rely on botkit.storage. then we could separate the two concerns, and have botkit initialize after we get a .then() from the promise of the drivers being ready.

**Comment by mvaragnat** [comment]
I don't think it's mandatory to use the botkit storage, indeed. You may be onto something. Perhaps you should fork this repo? If you could demo your idea with promises+more flexible storage, that would be awesome

**Pull request closed without merging**
